# Generated by Django 4.1.7 on 2023-02-26 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='web3_address',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='/uploads/users/default_img.png', upload_to='<django.db.models.fields.related.ForeignKey>/profile')),
                ('shop_bg_photo', models.ImageField(blank=True, upload_to='<django.db.models.fields.related.ForeignKey>/profile')),
                ('about_me', models.CharField(max_length=640)),
                ('featured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
