# Generated by Django 4.1.7 on 2023-02-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_wallet_balance_wallet_web3_address_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='web3_address',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
