# Generated by Django 4.1.7 on 2023-02-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_balance_profile_web3_address_delete_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/users/default_img.png', upload_to='<django.db.models.fields.related.ForeignKey>/profile'),
        ),
    ]
