# Generated by Django 4.1.7 on 2023-02-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_about_me_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured_slide',
            field=models.ImageField(blank=True, upload_to='<django.db.models.fields.related.ForeignKey>/profile'),
        ),
    ]
