# Generated by Django 4.1.7 on 2023-02-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumpost_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpost',
            old_name='created_date',
            new_name='created',
        ),
    ]
