# Generated by Django 4.1.7 on 2023-02-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_asset_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='creator',
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
    ]
