# Generated by Django 4.1.6 on 2023-02-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_slideshow_alter_listings_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slideshow',
        ),
    ]
