# Generated by Django 4.1.6 on 2023-02-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_slideshow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slideshow',
            new_name='Slide',
        ),
    ]
