# Generated by Django 4.1.6 on 2023-02-14 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0005_rename_slideshow_slide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Asset',
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='market_slideshow/'),
        ),
    ]
