# Generated by Django 4.1.6 on 2023-02-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_rename_listings_asset_alter_slide_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='key',
        ),
        migrations.AddField(
            model_name='asset',
            name='creator',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
