# Generated by Django 4.1.7 on 2023-02-16 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0007_remove_asset_key_asset_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='welcome',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('asset', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
