# Generated by Django 4.1.7 on 2023-02-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_slide_featured_slide_welcome_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
